Tomas update only hi message
pantheraworks/club-de-la-hamburguesa-bot pull request #4
Opened 2024-07-15 22:01 UTC by tomas-gonz

2024-07-16 08:24 UTC, matias-gonz commented on src/User.ts
> +    this.lastMessageTime = -(3 * 60 * 60 * 1000);
Deberias recibir el time o un time getter

2024-07-17 15:27 UTC, matias-gonz requested changes

2024-07-17 15:27 UTC, matias-gonz commented on src/Controller.ts
> +      user = new User(message.from, message.sender.pushname || '', -(3 * 60 * 60 * 1000));
Pero esto no deberia ser now()?

2024-07-17 15:27 UTC, matias-gonz commented on src/User.ts
> +    if(currentTime - this.lastMessageTime > twoHours) {
Cambia a una guard clause

2024-07-19 01:31 UTC, tomas-gonz commented on src/Controller.ts
> +      user = new User(message.from, message.sender.pushname || '', -(3 * 60 * 60 * 1000));
si la condicion del if es verdadera, me encuentro en el caso donde se está agregando un user nuevo, por lo tanto, recien se esta creando el user y todavia no se le mandó el link del pedido. Entonces en user.handleMessage() me va a llegar para ese caso que la hora es de -3horas., y si o si, el user nuevo está en el caso en el que se le debe mandar el link para hacer el pedido. Si se pusiese un now(), al comparar seria un now() - now(), lo que es menor que 2 horas y no enviaría el link del menu.

2024-07-19 14:49 UTC, matias-gonz approved these changes

2024-07-19 14:49 UTC, matias-gonz commented on src/Controller.ts
> +      user = new User(message.from, message.sender.pushname || '', -(3 * 60 * 60 * 1000));
Understandable 👍

2024-07-19 14:49 UTC, merged